### PR TITLE
Feature/project finalization

### PR DESCRIPTION
**Pull request by SaadMahi**
project at final stage, kindly review so we can merge this project to master branch

### CODE REVIEW

**Review by ManSOorcode — COMMENTED** [review]
Fix this!

IMG_20231016_234511

**Review by ManSOorcode — APPROVED** [review]
You have done very nice project keep going...

**Comment by SaadMahi** [comment]
> You have done very nice project keep going...

Thank you! Your assistance during the project was invaluable 😊

**Comment by SaadMahi** [comment]
> IMG_20231016_234511

> [🐛 fix: avg run time of movies in watched list](https://github.com/SaadMahi/61-PopcornPicks/pull/14/commits/4a32dc9113f4f01d5dcefbbfcada2d28d9ef955f)

issue fixed

**Pull request merged**
